name: Dev Shell

on:
  workflow_call:

jobs:
  discover:
    name: Discover templates
    runs-on: ubuntu-24.04
    outputs:
      templates: ${{ steps.list.outputs.templates }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: List templates
        id: list
        run: |
          templates=$(find templates -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort | jq -Rc '[.,inputs]')
          echo "templates=$templates" >> "$GITHUB_OUTPUT"

  devshell-build:
    name: Build devShell (${{ matrix.template }})
    needs: discover
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        template: ${{ fromJson(needs.discover.outputs.templates) }}

    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
          - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31

      - uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: rito528-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build devShell
        run: nix build ./templates/${{ matrix.template }}#devShells.x86_64-linux.default
