name: Dev Shell

on:
  workflow_call:

jobs:
  discover:
    name: Discover templates
    runs-on: ubuntu-24.04
    outputs:
      templates: ${{ steps.list.outputs.templates }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: List templates
        id: list
        run: |
          templates=$(find templates -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort | jq -Rc '[.,inputs]')
          echo "templates=$templates" >> "$GITHUB_OUTPUT"

  devshell-build:
    name: Build devShell (${{ matrix.template }})
    needs: discover
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        template: ${{ fromJson(needs.discover.outputs.templates) }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: rito528-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build devShell
        run: nix build ./templates/${{ matrix.template }}#devShells.x86_64-linux.default
