name: Docs

on:
  workflow_call:

jobs:
  docs-build:
    name: Docs Build
    runs-on: ubuntu-24.04
    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
          - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Build mdBook site
        run: nix shell nixpkgs#mdbook --command mdbook build docs-site
