name: EditorConfig

on:
  workflow_call:

jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-24.04
    steps:
      - parallel:
          - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

          - name: Set up editorconfig-checker
            uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c # main

      - name: Check editorconfig
        run: editorconfig-checker
