name: Nix

on:
  workflow_call:

jobs:
  nix-flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-26.04
    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
          - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

      - uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: rito528-dotfiles
      - parallel:
          - name: Check nixfmt formatting
            run: |
              find . -name "*.nix" -not -path "./.git/*" -type f -print0 | \
                xargs -0 nix run nixpkgs#nixfmt -- --check

          - name: Run nix flake check
            run: nix flake check .

          - name: Evaluate darwin home-manager config
            run: nix eval .#darwinConfigurations.testuser-darwin.config.home-manager.users.testuser.home.username
