name: Nix

on:
  push:
    branches: [main]
    paths:
      - '**/*.nix'
      - 'flake.lock'
      - '.github/workflows/nix.yaml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.nix'
      - 'flake.lock'
      - '.github/workflows/nix.yaml'

jobs:
  nix-flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Check nixfmt formatting
        run: |
          find . -name "*.nix" -not -path "./.git/*" -type f | \
            xargs nix run nixpkgs#nixfmt -- --check
      - run: nix flake check .
