name: Nix

on:
  workflow_call:

jobs:
  nix-flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: rito528-dotfiles
      - name: Check nixfmt formatting
        run: |
          find . -name "*.nix" -not -path "./.git/*" -type f -print0 | \
            xargs -0 nix run nixpkgs#nixfmt -- --check
      - run: nix flake check .
